### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by theseeker99** [weebzone/WZML#100]
2023-01-02 22:03:10,319 - bot - INFO - Generating SESSION_STRING
2023-01-02 22:03:11,835 - pyrogram.connection.connection - INFO - Connecting...
2023-01-02 22:03:11,993 - pyrogram.connection.connection - INFO - Connected! Production DC5 - IPv4
2023-01-02 22:03:11,996 - pyrogram.session.session - INFO - NetworkTask started
2023-01-02 22:03:12,734 - pyrogram.session.session - INFO - Session initialized: Layer 151
2023-01-02 22:03:12,735 - pyrogram.session.session - INFO - Device: CPython 3.8.10 - Pyrogram 2.0.93
2023-01-02 22:03:12,735 - pyrogram.session.session - INFO - System: Linux 5.15.0-25-generic (en)
2023-01-02 22:03:12,735 - pyrogram.session.session - INFO - Session started
2023-01-02 22:03:12,852 - pyrogram.session.session - INFO - PingTask started
2023-01-02 22:03:13,466 - bot - INFO - Telegram Premium Detected! Leech Limit upgraded to 4GB
2023-01-02 22:03:13,468 - bot - INFO - TG_SPLIT_SIZE: 4194304000
[2023-01-02 22:03:13 +0000] [39] [INFO] Starting gunicorn 20.1.0
[2023-01-02 22:03:13 +0000] [39] [INFO] Listening at: http://0.0.0.0:81 (39)
[2023-01-02 22:03:13 +0000] [39] [INFO] Using worker: sync
[2023-01-02 22:03:13 +0000] [61] [INFO] Booting worker with pid: 61
2023-01-02 22:03:14,745 - root - INFO - Initializing Aria2c
2023-01-02 22:03:16,511 - bot - INFO - Creating Telegraph Account
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 18, in <module>
    from .helper.ext_utils.bot_utils import get_readable_file_size, get_readable_time
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 12, in <module>
    from bot.helper.telegram_helper.bot_commands import BotCommands
  File "/usr/src/app/bot/helper/telegram_helper/bot_commands.py", line 1, in <module>
    from bot import CMD_PERFIX
ImportError: cannot import name 'CMD_PERFIX' from 'bot' (/usr/src/app/bot/__init__.py)

**Comment by MajnuRangeela** [comment]
It doesn't look like you have deployed correct repo. Don't create your personal repo issues here !
