### ISSUE TITLE
About This Error I Can't Start The Bot

### ISSUE THREAD

**Issue by TEMohanish** [weebzone/WZML#108]
Traceback (most recent call last):                File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main                              mod_name, mod_spec, code = _get_module_details(mod_name, _Error)                              File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details                              return _get_module_details(pkg_main_name, error)                                              File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    import(pkg_name)                          File "/home/ubuntu/mirrorbot/bot/init.py", line 95, in <module>
    if config_dict := db.settings.config.find_one({'_id': bot_id}):  #retrun config dict (all env vars)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/collection.py", line 1459, in find_one
    for result in cursor.limit(-1):               File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.data) or self._refresh():       File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/cursor.py", line 1139, in _refresh                                                  self.session = self.__collection.database.client._ensure_session()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1740, in _ensure_session                                     return self.start_session(True, causal_consistency=False)                                   File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1685, in start_session                                     self._topology._check_implicit_session_support()                                              File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support                          self._check_session_support()                 File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/topology.py", line 554, in _check_session_support                                   self._select_servers_loop(                    File "/home/ubuntu/.local/lib/python3.8/site-packages/pymongo/topology.py", line 238, in _select_servers_loop                                     raise ServerSelectionTimeoutError(          pymongo.errors.ServerSelectionTimeoutError: ac-rlhq1g0-shard-00-01.amfpcpd.mongodb.net:27017: ,ac-rlhq1g0-shard-00-02.amfpcpd.mongodb.net:27017: ,ac-rlhq1g0-shard-00-00.amfpcpd.mongodb.net:27017: , Timeout: 30s, Topology Description: <TopologyDescription id: 63b81631361e6edcce730faa, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-rlhq1g0-shard-00-00.amfpcpd.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-rlhq1g0-shard-00-00.amfpcpd.mongodb.net:27017: ')>, <ServerDescription ('ac-rlhq1g0-shard-00-01.amfpcpd.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-rlhq1g0-shard-00-01.amfpcpd.mongodb.net:27017: ')>, <ServerDescription ('ac-rlhq1g0-shard-00-02.amfpcpd.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-rlhq1g0-shard-00-02.amfpcpd.mongodb.net:27017: ')>]>

**Comment by MajnuRangeela** [comment]
Redeploy with new mongodb URL
