### ISSUE TITLE
/scrape option is creating issue on webseries or more links if listed 

### ISSUE THREAD

**Issue by satyamisme** [weebzone/WZML#17]
**Describe the bug**
The bot failed to load on /scrape option 

list of links are displayed some times and failed most of the time when processed webseries 
ex - 

https://htpmovies.lol/hostages-2019-web-series-download-in-telugu-tamil-hindi-malayalam-kannada-hd-s01-s02-all-episodes-480p-720p-1080p/

**To Reproduce**
1. Go to '/scrape [link](https://htpmovies.lol/hostages-2019-web-series-download-in-telugu-tamil-hindi-malayalam-kannada-hd-s01-s02-all-episodes-480p-720p-1080p/) '

2. See error

**Expected behavior**
expected output result of links 

**Screenshots**
Running scrape. Wait about some secs.

**Additional context**

error in log 

2022-10-29 10:12:35,015 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/scraper.py", line 73, in scrapper
    prsd += htpmovies(url) + '\n\n'
  File "/usr/src/app/bot/modules/scraper.py", line 143, in htpmovies
    title = soup.title.get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'

*Option request*

please add option to display progress of links processing

**Comment by SilentDemonSD** [comment]
Working On...

**Comment by weebzone** [comment]
fixed now
