### ISSUE TITLE
Speedtest Module error

### ISSUE THREAD

**Issue by theseeker99** [weebzone/WZML#34]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/speedtest.py", line 15, in speedtest
    test = Speedtest()
  File "/usr/local/lib/python3.8/dist-packages/speedtest.py", line 1095, in __init__
    self.get_config()
  File "/usr/local/lib/python3.8/dist-packages/speedtest.py", line 1127, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: HTTP Error 403: Forbidden

How to fix this?

**Comment by weebzone** [comment]
HTTP Error 403 means site is blocked on that server
