### ISSUE TITLE
NameError: name 'help_user' is not defined

### ISSUE THREAD

**Issue by oktest145** [weebzone/WZML#37]
Bot crash on using /help

2022-11-25 04:16:41,400 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/__main__.py", line 334, in bot_help
    button.buildbutton("User", f"https://graph.org/{help_user}")
NameError: name 'help_user' is not defined

**Comment by weebzone** [comment]
fixed now
