### ISSUE TITLE
Indentation Error

### ISSUE THREAD

**Issue by pachax001** [weebzone/WZML#54]
File "/usr/src/app/bot/modules/bot_settings.py", line 245
mirrorbot-app-1  |     TORRENT_TIMEOUT = ''
mirrorbot-app-1  |                        ^
mirrorbot-app-1  | IndentationError: unindent does not match any outer indentation level

**Comment by alonelove7** [comment]
root@s10881442:~/WZML-master# sudo docker run -p 200:200 mltb
2022-12-03 18:01:07,858 - dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 155
2022-12-03 18:01:08,864 - dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 155
2022-12-03 18:01:08,927 - bot - INFO - Generating SESSION_STRING
2022-12-03 18:01:08,928 - bot - INFO - TG_SPLIT_SIZE: 2097151000
2022-12-03 18:01:08,928 - root - WARNING - BASE_URL not provided!
2022-12-03 18:01:09,529 - root - INFO - Initializing Aria2c
2022-12-03 18:01:11,262 - bot - INFO - Creating Telegraph Account
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 25, in <module>
    from .modules import authorize, list, cancel_mirror, mirror_status, mirror_leech, clone, ytdlp, shell, eval, bot_settings, \
  File "/usr/src/app/bot/modules/bot_settings.py", line 245
    TORRENT_TIMEOUT = ''

**Comment by weebzone** [comment]
@alonelove7 fixed now

**Comment by weebzone** [comment]
@pachax001 fixed now
