### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by alonelove7** [weebzone/WZML#55]
Hi dear
still for some files on telegram 
status of these file gets stuck on 100% 
/leech and /mirror  command
Unfortunately no Error in log file
├[████████████▄] 100.0%

**Comment by alonelove7** [comment]
2022-12-04 14:10:01,908 - bot.helper.mirror_utils.upload_utils.pyrogramEngine - INFO - Leech Completed: rose-17.480.mp4
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 122, in add_download
    self.__download(_dmsg, path)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 81, in __download
    self.__onDownloadComplete()
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 69, in __onDownloadComplete
    self.__listener.onDownloadComplete()
  File "/usr/src/app/bot/modules/listener.py", line 216, in onDownloadComplete
    tg.upload(o_files)
  File "/usr/src/app/bot/helper/mirror_utils/upload_utils/pyrogramEngine.py", line 75, in upload
    self.__listener.onUploadComplete(None, size, self.__msgs_dict, self.__total_files, self.__corrupted, self.name)
  File "/usr/src/app/bot/modules/listener.py", line 307, in onUploadComplete
    reply_to.delete()
  File "/usr/local/lib/python3.8/dist-packages/telegram/message.py", line 2433, in delete
    return self.bot.delete_message(
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 579, in delete_message
    result = self._post('deleteMessage', data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message can't be deleted
