### ISSUE TITLE
py mongo is going of charts as far i know i tried 3 diffrent m bots everyone of them got this 

### ISSUE THREAD

**Issue by steve472-art** [weebzone/WZML#65]
**Describe the bug**

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 85, in add_download
    media = _dmsg.document or _dmsg.video or _dmsg.audio or None
AttributeError: 'NoneType' object has no attribute 'document'

**To Reproduce**
1. Just run the bot and try to leech anything
2. See error

**Expected behavior**
welp

**Comment by steve472-art** [comment]
sorry im an idiot
