### ISSUE TITLE
Not uploading to gdrive

### ISSUE THREAD

**Issue by theseeker99** [weebzone/WZML#75]
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/qbit_downloader.py", line 194, in __check_limits
    acpt = check_storage_threshold(size, arch)
  File "/usr/src/app/bot/helper/ext_utils/fs_utils.py", line 94, in check_storage_threshold
    if disk_usage(DOWNLOAD_DIR).free - size < STORAGE_THRESHOLD * 1024**3:
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by weebzone** [comment]
will fixed on next update
