### ISSUE TITLE
New Error occuring since last night.

### ISSUE THREAD

**Issue by yopremium21** [weebzone/WZML#98]
**New error occured and build is failed since last night. I downloaded latest script from this repo and still this error is happening. Kindly look into it.
I am providing log detail for your reference**

2023-01-02 04:16:08,376 - bot - INFO - Generating SESSION_STRING
2023-01-02 04:16:08,378 - root - INFO - Initializing Aria2c
Initiliazing Library with API_KEY: SzxWmAqB
2023/01/02 04:16:08 Serving on TCP :6090
[GIN] 2023/01/02 - 04:16:15 | 200 |  3.807912474s |       127.0.0.1 | POST     "/login"
2023-01-02 04:16:15,196 - bot - INFO - TG_SPLIT_SIZE: 2097151000
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 908, in <module>
    updater = tgUpdater(token=BOT_TOKEN, request_kwargs={'read_timeout': 20, 'connect_timeout': 15})
TypeError: Updater.__init__() got an unexpected keyword argument 'token'
2023-01-02 04:16:31,678 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f21ff299120>

**Comment by MajnuRangeela** [comment]
Redeploy with latest commit!
